apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-publisher-service
spec:
  type: ClusterIP
  selector:
    app: rabbitmq-publisher
  ports:
    - port: 8085
      targetPort: 8085
     # nodePort: 30010